spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
server:
  port: 8081